name: CI Job
on:
  workflow_run:
    workflows: ["Application build"]
    types:
      - completed
env:
  TOKEN: ${{ secrets.TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 18
        - name: Install
          run: npm install
        - name: Test
          run: npm run test
        - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: logs
            path: logs
        - name: Get Allure history
          uses: actions/checkout@v2
          if: always()
          continue-on-error: true
          with:
              ref: gh-pages
              path: gh-pages
        # - uses: actions/upload-artifact@v3
        #   with:
        #     name: allureReport

        #     path: 
        #       ./allure-report
        - name: Allure Report action from marketplace
          uses: simple-elf/allure-report-action@master
          if: always()
        #id: allure-report
          with:
                 allure_results: allure-results
          #gh_pages: gh-pages
          #allure_report: allure-report
                 allure_history: allure-history
                 keep_reports: 1
        
          
        - name: Deploy report to Github Pages
          if: always()
          uses: peaceiris/actions-gh-pages@v2
          env:
           PERSONAL_TOKEN: TOKEN
           PUBLISH_BRANCH: gh-pages
           
           PUBLISH_DIR: allure-history
