name: CI
on: [pull_request,push]
env:
  WF_ENV: Avilable to all in the project
jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      JOB_ENV: Avilable for jobs only   
    steps:
        
        - name: Checkout
          
          uses: actions/checkout@v3
          
        - uses: actions/setup-node@v3
          with:
            node-version: 16
 
        - name: Test
          run: |
            cd ${GITHUB_WORKSPACE}/Learn-Portal
            pwd
            npm install
            npm rebuild
            npx cross-env ENV=uat envSpecific=learn testrail=no slackNotification=no emailNotification=no runEnv=local slackNotification=no wdio run ./wdio.conf.js --spec test/Smoke_Suite/SignUp_SmokeTest.js
            
        - uses: actions/upload-artifact@v2
          if: failure()
          with:
            name: gh-pages
            path: gh-pages
      
        - name: Get Allure history
          uses: actions/checkout@v2
          if: always()
          
          continue-on-error: true
          with:
              ref: gh-pages
              path: gh-pages
       
        - name: Allure Report action from marketplace
          uses: simple-elf/allure-report-action@master
          if: always()
          #id: allure-report
          with:
                 allure_results: Learn-Portal/allure-results
                 allure_history: Learn-Portal/allure-history
                 keep_reports: 5
      
    
          
        - name: Deploy report to Github Pages
          if: always()
          uses: peaceiris/actions-gh-pages@v2
          
          env:
           PERSONAL_TOKEN: ${{ secrets.TOKEN }}
           PUBLISH_BRANCH: gh-pages
           PUBLISH_DIR: Learn-Portal/allure-history
